name: Build mini-fps for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install mingw
        uses: msys2/setup-msys2@v2

      - name: Build game
        env:
          CC: gcc
          CXX: g++
        run: |
          mkdir ci-build
          cmake -G "CodeBlocks - MinGW Makefiles" -S . -B ci-build
          cd ci-build
          mingw32-make

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: mini-fps-windows
          path: ci-build/mini-fps-windows