name: Build mini-fps for macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        architecture: [ x86_64, arm64 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install meson ninja

      - name: Copy frameworks to Library
        run: |
          MACOS_SDK_PATH=$(xcrun --show-sdk-path)
          sudo mkdir $MACOS_SDK_PATH/System/Library/Frameworks/SDL2.framework
          sudo mkdir $MACOS_SDK_PATH/System/Library/Frameworks/SDL2_image.framework
          sudo cp -R lib/* $MACOS_SDK_PATH/System/Library/Frameworks

      - name: Remove build directory if it exists
        run: if [ -d bin/ ]; then rm -rf bin/; fi

      - name: Create build directory
        run: mkdir bin

      - name: Setup Meson environment
        run: meson setup bin . --wipe --prefix="$(pwd)/bin/mini-fps.app" --bindir='Contents/MacOS'

      - name: Build game
        run: |
          cd bin
          meson install

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: mini-fps-${{ matrix.architecture }}
          path: bin/