name: Build MiniFPS for macOS

on:
  push:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print system configuration
        run: uname -a

      - name: Install dependencies
        run: brew install meson ninja

      - name: Copy frameworks to Library
        run: |
          MACOS_SDK_PATH=$(xcrun --show-sdk-path)
          sudo mkdir $MACOS_SDK_PATH/System/Library/Frameworks/SDL2.framework
          sudo mkdir $MACOS_SDK_PATH/System/Library/Frameworks/SDL2_image.framework
          sudo mkdir $MACOS_SDK_PATH/System/Library/Frameworks/SDL2_mixer.framework
          sudo mkdir $MACOS_SDK_PATH/System/Library/Frameworks/SDL2_ttf.framework
          sudo cp -R lib/* $MACOS_SDK_PATH/System/Library/Frameworks

      - name: Remove build directory if it exists
        run: if [ -d bin/ ]; then rm -rf bin/; fi

      - name: Create build directory
        run: mkdir bin

      - name: Setup Meson environment
        run: meson setup bin . --wipe --prefix="$(pwd)/bin/MiniFPS.app" --bindir='Contents/MacOS'

      - name: Build game
        run: |
          cd bin
          meson install

      - name: Run install_name_tool
        run: |
          MACOS_SDK_PATH=$(xcrun --show-sdk-path)
          cd bin/MiniFPS.app/Contents/MacOS
          install_name_tool -change @rpath/SDL2.framework/Versions/A/SDL2 ../Frameworks/SDL2.framework/Versions/A/SDL2 MiniFPS
          install_name_tool -change @rpath/SDL2_image.framework/Versions/A/SDL2_image ../Frameworks/SDL2_image.framework/Versions/A/SDL2_image MiniFPS
          install_name_tool -change @rpath/SDL2_ttf.framework/Versions/A/SDL2_ttf ../Frameworks/SDL2_ttf.framework/Versions/A/SDL2_ttf MiniFPS

      - name: Set executable permissions
        run: |
          cd bin/MiniFPS.app/Contents/MacOS
          chmod +x MiniFPS.sh
          chmod +x MiniFPS

      - name : Tar app
        run: tar -cvf MiniFPS.tar -C bin/ --exclude='.DS_Store' MiniFPS.app

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: MiniFPS-macOS
          path: MiniFPS.tar