name: Build mini-fps for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Mingw
        uses: msys2/setup-msys2@v2

      - name: Build CMake project
        env:
          CC: gcc
          CXX: g++
        run: |
          mkdir ci-build
          cd ci-build
          cmake ..
          cmake -G "MinGW Makefiles" ..
          mingw32-make

      - name: List
        run: dir

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: mini-fps-windows
          path: mini-fps.tar