name: Build mini-fps for macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        architecture: [ x86_64 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print system configuration
        run: uname -a

      - name: Install dependencies
        run: brew install meson ninja

      - name: Copy frameworks to Library
        run: |
          MACOS_SDK_PATH=$(xcrun --show-sdk-path)
          sudo mkdir $MACOS_SDK_PATH/System/Library/Frameworks/SDL2.framework
          sudo mkdir $MACOS_SDK_PATH/System/Library/Frameworks/SDL2_image.framework
          sudo cp -R lib/* $MACOS_SDK_PATH/System/Library/Frameworks

      - name: Remove build directory if it exists
        run: if [ -d bin/ ]; then rm -rf bin/; fi

      - name: Create build directory
        run: mkdir bin

      - name: Setup Meson environment
        run: meson setup bin . --wipe --prefix="$(pwd)/bin/mini-fps.app" --bindir='Contents/MacOS'

      - name: Build game
        run: |
          cd bin
          meson install

      - name: Run install_name_tool
        run: |
          MACOS_SDK_PATH=$(xcrun --show-sdk-path)
          cd bin
          install_name_tool -change @rpath/SDL2.framework/Versions/A/SDL2 ../Frameworks/SDL2.framework/SDL2/Versions/A/SDL2 mini-fps.app/Contents/MacOS/mini-fps
          install_name_tool -change @rpath/SDL2_image.framework/Versions/A/SDL2_image ../Frameworks/SDL2_image.framework/SDL2_image/Versions/A/SDL2_image mini-fps.app/Contents/MacOS/mini-fps

      - name: Set executable permissions
        run: |
          cd bin/mini-fps.app/Contents/MacOS
          chmod +x mini-fps.sh
          chmod +x mini-fps

      - name : Tar app
        run: tar -cvf mini-fps.tar -C bin/ --exclude='.DS_Store' mini-fps.app

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: mini-fps-macOS-${{ matrix.architecture }}
          path: mini-fps.tar