name: Build MiniFPS for Windows

on:
  push:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install mingw
        uses: msys2/setup-msys2@v2

      - name: Build game
        env:
          CC: gcc
          CXX: g++
        run: |
          mkdir bin
          cmake -G "CodeBlocks - MinGW Makefiles" -S . -B bin
          cd bin
          mingw32-make

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: MiniFPS-windows
          path: bin/MiniFPS-windows